config/routes.rb
Rails.application.routes.draw do
  root 'staticpages#home'
  get '/about', to: 'staticpages#about'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  delete '/logout', to: 'sessions#destroy'

  resources :users
  # resources :sessions, only: :create
  post '/sessions', to: 'sessions#create'
  resources :microposts, only: :create
  resources :relationships, only: [:create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user
  validates :content, presence: true, length: { maximum:250 }
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # validates :name, presence: true, length: { maximum: 50 }

  has_many :microposts, dependent: :destroy
  #Filter method to transform email to small cases before saving to db
  before_save {email.downcase!}

  validates :name, presence: true, length: { maximum: 50 }

  #REGEX = Regular Expression
  #To validate correct email structure
  EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i

  validates :email, presence: true, length: { maximum: 255 },
                                    format: { with: EMAIL_REGEX },
                                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  has_many :active_relationships, class_name: "Relationship",
                                  foreign_key: "follower_id",
                                  dependent: :destroy

  has_many :passive_relationships, class_name: "Relationship",
                                  foreign_key: "followed_id",
                                  dependent: :destroy

  has_many :following, through: :active_relationships, source: :followed
  has_many :follower, through: :passive_relationships, source: :follower

  # Follows a user
  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end

  # Unfollows a user
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  # Returns true if the current user is following the other user
  def following?(other_user)
    following.include?(other_user)
  end

  # Returns a user's status feed
  def feed
    Micropost.where("user_id IN (?) OR user_id = ?", following_ids, id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  def create
    @micropost = current_user.microposts.build(micropost_params)
    if @micropost.save
      flash[:success] = "Microposts Created!"
      redirect_to root_url
    else
      @microposts = current_user.microposts
      render "users/home_feeds"
    end

  end

  # string parameter

  private
    def micropost_params
      params.require(:micropost).permit(:content)
    end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create 
    user = User.find(params[:followed_id])
    current_user.follow(user)
    redirect_to user
  end

  def destroy
    user = Relationship.find(params[:id]).followed
    current_user.unfollow(user)
    redirect_to user
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email])

    if user && user.authenticate(params[:session][:password])
      log_in(user)
      flash[:success] = "Succesfully logged in."
      redirect_to root_url
    else
      flash.now[:danger] = "Invaid Credentions."
      render 'new'
    end
  end

  def destroy
    log_out
    flash[:info] = "Successfully logged out"
    redirect_to root_url
  end

end

app/controllers/staticpages_controller.rb
class StaticpagesController < ApplicationController
  def home
    if logged_in?
      @micropost = Micropost.new
      @microposts = current_user.feed
      render 'users/home_feeds'
    else
      render 'staticpages/home'
    end
  end

  def about
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.paginate(page: params[:page], per_page: 10)
  end

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
    @microposts = @user.microposts
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to root_url
    else
      render "new"
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to user_url(@user)
    else
      render 'new'
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_url
  end


# string parameter

  private
    def user_params
      params.require(:user).permit(:name, :email, :password,
      :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def log_out
    session.delete(:user_id)
  end

  def current_user
    User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end
end

app/helpers/staticpages_helper.rb
module StaticpagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user)
    #Generate hex token
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"

    image_tag(gravatar_url, alt: user.name)
  end
end

app/views/layouts/_footer.html.erb
<footer class="border-top p-3">
    <div class="container">
        <small class="float-left">Awesomeblog application</small>

        <ul class="float-right ">
            <li class="d-inline-block mr-2">
                <%= link_to "Home", root_path, class: "text-muted" %>
            </li>
            <li class="d-inline-block mr-2">
                <%= link_to "About", about_path, class: "text-muted" %>
            </li>
            <li class="d-inline-block mr-2">
                <%= link_to "Signup", signup_path, class: "text-muted" %>
            </li>
            <li class="d-inline-block mr-2">
                <%= link_to "Login", login_path, class: "text-muted" %>
            </li>
        </ul>
    </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <div class="container mb-1">
        <strong><%= link_to 'awesomeblog', root_path, class: "navbar-brand"%></strong>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown">
            <span class="navbar-toggler-icon"></span>
        </button>


<%# bootstrapの<a>タグのところをrubyのlink_toに変える。見せる部分だけ<%= %>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <%= link_to "Home", root_path, class: "nav-link" %>
                </li>
                <li class="nav-item">
                    <%= link_to "About", about_path, class: "nav-link" %>
                </li>

                <% if logged_in?%>
                    <li class="nav-item">
                        <%= link_to "Users", users_path, class: "nav-link" %>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <%= current_user.name %>
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <%= link_to "Profile", current_user, class: "dropdown-item" %>
                            <%= link_to "Settings", edit_user_path(current_user), class: "dropdown-item" %>
                            <div class="dropdown-divider" ></div>
                            <%= link_to "Logout", logout_path, method: :delete, class: "dropdown-item" %>
                        </div>
                    </li>
                <% else %>
                    <li class="nav-item">
                        <%= link_to "Signup", signup_path, class: "nav-link" %>
                    </li>
                    <li class="nav-item">
                        <%= link_to "Login", login_path, class: "nav-link" %>
                    </li>
                <% end %>
            </ul>
        </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>AwesomeBlog</title>
        <%= csrf_meta_tags %>
        <%= csp_meta_tag %>
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
        <link href="https://fonts.googleapis.com/css?family=Ibarra+Real+Nova&display=swap" rel="stylesheet">
    </head>

    <body>
        <%= render 'layouts/header' %>
        <div class="container p-3">
            <% if flash.any? %>
                <% flash.each do |type, msg|%>
                <div class="alert alert-<%= type %>">
                    <div><%= msg %></div>
                </div>
                <% end %>
            <% end %>

            <%= yield %>

            <%= debug session[:user_id] if Rails.env == 'development' %>
        </div>
        <%= render 'layouts/footer' %>
    </body>
</html>

app/views/microposts/_micropost.html.erb
<% @microposts.each do |micropost| %>
    <li class="media mb-4">
        <div class="mr-2">
            <%# 写真と名前を押してもリンクで戻れる %>
            <%= link_to gravatar_for(micropost.user), user_url(micropost.user) %>
        </div>

        <div class="media-body">
            <h5><%= link_to micropost.user.name, micropost.user %></h5>
            <div><%= micropost.content %></div>
            <small class="text-muted">Posted <%= time_ago_in_words(micropost.created_at) %> ago </small>
        </div>
    </li>
    <hr>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
    <div class="alert alert-danger">
        The form contains <%= pluralize(object.errors.count, "error") %>
    </div>
    <ul>
        <% object.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
    </ul>
    <hr>
<% end %>

app/views/staticpages/about.html.erb
<div class="jumbotron">
    <h1><strong>About</strong></h1>
    <p>This is a Ruby on Rails application.</p>
</div>

app/views/staticpages/home.html.erb
<div class="jumbotron">
    <h1><strong>Awesomeblog app</strong></h1>
    <p>Welcome to Awesomeblog!</p>
</div>

app/views/users/_form.html.erb
<%= form_for (@user) do |f| %>
    <%= render "shared/error_messages", object: f.object %>
    <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control" %>
    </div>
    <div class="form-group">
        <%= f.label :email %>
        <%= f.email_field :email, class: "form-control" %>
    </div>
    <div class="form-group">
        <%= f.label :password %>
        <%= f.password_field :password, class: "form-control" %>
    </div>
    <div class="form-group mb-4">
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation, class: "form-control" %>
    </div>
    <%= f.submit "Create an acount", class: "btn btn-primary btn-block" %>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<div class="col-6 mx-auto">
    <div class="jumbotron opacity pt-2 pb-5 mt-4">
        <h1 class="text-center m-4">Update Account</h1>
        <%= form_for (@user) do |f| %>
            <div class="form-group ">
                <%= f.label :name %>
                <%= f.text_field :name, class: "form-control" %>
            </div>
            <div class="form-group">
                <%= f.label :email %>
                <%= f.email_field :email, class: "form-control" %>
            </div>
            <div class="form-group">
                <%= f.label :password %>
                <%= f.password_field :password, class: "form-control" %>
            </div>
            <div class="form-group mb-4">
                <%= f.label :password_confirmation %>
                <%= f.password_field :password_confirmation, class: "form-control" %>
            </div>
            <%= f.submit "Edit acount", class: "btn btn-primary btn-block" %>
        <% end %>
    </div>
</div>

app/views/users/home_feeds.html.erb
<div class="row">
    <div class="col-4">
        <div class="card mb-3">
            <div class="card-body text-center">
                <%= gravatar_for current_user %>
                <h1 class="mt-2"><%= current_user.name %></h1>
                <%= current_user.email %>
            </div>
            <hr>
            <div class="card">
                <div class="card-header">
                    <%= form_for (@micropost) do |f| %>
                        <%= render "shared/error_messages", object: f.object %>
                        <div class="form-group">
                            <%= f.text_area :content, class: "form-control", placeholder:"Share your toughts..." %>
                        </div>
                        <div class="mt-3">
                            <%= f.submit "POST", class: "btn btn-primary btn-block" %>
                        </div>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
    <div class="col-8">
        <div class="card">
            <div class="card-body">
                <h2 class="border-bottom pb-4">Feed</h2>
                <% if @microposts.any? %>
                    <ul class = "list-unstyled">
                        <%= render 'microposts/micropost' %>
                    </ul>
                <% else %>
                    <div class="text-muted"> Nothing to show </div>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/users/index.html.erb
<h1 class="text-center mt-3">Members</h1>

<div class="row mt-4">
    <% @users.each do |user| %>
        <div class="col-6">
            <div class="media mb-3">
                <%= gravatar_for(user) %>
                <div class="media-body">
                    <h5 class="pl-2 font-weight-bold"><%= link_to user.name, user %> </h5>
                </div>
                <% if current_user.admin? %>
                    <%= link_to "Delete",user_path(user), method: :delete, class: "btn btn-outline-danger btn-sm", data: { confirm: "Are you sure?"} %>
                <% end %>
            </div>
        </div>
    <% end %>
</div>

<div class="paginate text-center mt-4">
    <%= will_paginate %>
</div>

app/views/users/new.html.erb
<div class="col-6 mx-auto">
    <h1 class="text-center m-4">Sign up</h1>
    <%= render 'form' %>
</div>

<%# 別にrenderのところに_form.html.erbの内容を書いても良い。でも、見にくいのでusersのフォルダー内でパーシャルをつけて
別フォルダ(ex _form.html.erb)に分けたほうがわかりやすいからそうしている。application.html.erbの中の_headerと_footerも同じ。 %>

app/views/users/show.html.erb
<div class="jumbotron">
    <div class="gravatar-img mb-2">
        <%= gravatar_for @user %>
    </div>
    <div class="row">
        <div class="col-8">
            <div class="media-body ml-3">
                <h1><%= @user.name %></h1>
                <p><%= @user.email %></p>
                <% if current_user != @user %>
                    <% unless current_user.following?(@user) %>
                        <%= form_for(current_user.active_relationships.build) do |f| %>
                            <div><%= hidden_field_tag :followed_id, @user.id %></div>
                            <%= f.submit "Follow", class: "btn btn-primary" %>
                        <% end %>
                    <% else %>
                        <%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
                        html: {method: :delete}) do |f| %>
                            <%= f.submit "Unfollow", class: "btn btn-primary" %>
                        <% end %>
                    <% end %>
                <% end %>
            </div>
        </div>
        <div class="col-4 text center">
            <div class="row">
                <div class="col-4">
                    <h3><%= @user.microposts.count %></h3>
                    microposts
                </div>
                <div class="col-4">
                    <h3><%= @user.active_relationships.count %> </h3>
                    following
                </div>
                <div class="col-4">
                    <h3><%= @user.passive_relationships.count %></h3>
                    follower
                </div>
            </div>
        </div>
    </div>
</div>

<div>
    <% if @microposts.any? %>
        <ul class = "list-unstyled">
            <%= render 'microposts/micropost' %>
        </ul>
    <% else %>
        <div class="text-muted"> Nothing to show </div>
    <% end %>
</div>